build:
    nodes:
        tests:
            environment:
                php:
                    version: 8.1.0
    tests:
        override:
            - php-scrutinizer-run

tools:
    external_code_coverage: true
